### ISSUE TITLE
Missing Config Files

### ISSUE THREAD

**Issue by ryftjet** [CrealityOfficial/Ender-3V3-SE#2]
Hi there @CrealityTech,
I'm just wondering if it's intentional that the configuration files are missing? I need them to compile Marlin, but in the link in `config/README.md` I can't find any configurations for the Ender 3 V3 SE.

Thanks!

**Comment by 4bes2** [comment]
They are already in the marlin folder. Just configure them from there.

**Comment by ryftjet** [comment]
Oh thanks so much! (sorry I'm blind apparently)
